[project]
name = "spatialid"
version = "1.0.0"
requires-python = ">=3.9.0"
dependencies = [
    "pyshp==2.3.0",
    "pyproj==3.3.1",
    "pybullet==3.2.5",
    "numpy==1.22.4",
    "scikit-spatial==6.4.0"
]
